/*
 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
*/

package FinalProject;


import java.text.DecimalFormat;

/**
 *
 * @author Daanyaal Ahad Saeed
 */

public class Customer_Select extends javax.swing.JFrame {

    public Customer_Select() {
        initComponents();
        setLocationRelativeTo(this);
        
        ArmChair_Total.setText("0.00");              //Initializes Arm Chair Field to 0.00
        Desk_Total.setText("0.00");                  //Initializes Desk Field to 0.00
        ChestOfDrawers_Total.setText("0.00");        //Initializes Chest of Drawers Field to 0.00
        Cupboard_Total.setText("0.00");              //Initializes Cupboard Field to 0.00
        TVBench_Total.setText("0.00");               //Initializes TV Bench Field to 0.00
        Sofa_Total.setText("0.00");                  //Initialiazes Sofa Field to 0.00
        CoffeeTable_Total.setText("0.00");           //Initialiazes Coffee Table Field to 0.00
        DinningTable_Total.setText("0.00");          //Initialiazes Dinning Table Field to 0.00
        BedFrame_Total.setText("0.00");              //Initialiazes Bed Frame Field to 0.00
        Chairs_Total.setText("0.00");                //Initialiazes Chairs Field to 0.00
        
    }
    
    
    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem5 = new javax.swing.JCheckBoxMenuItem();
        checkbox1 = new java.awt.Checkbox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Sofa_Item = new javax.swing.JCheckBox();
        BedFrame_Item = new javax.swing.JCheckBox();
        Next_Button = new javax.swing.JButton();
        CoffeeTable_Item = new javax.swing.JCheckBox();
        Chairs_Item = new javax.swing.JCheckBox();
        DinningTable_Item = new javax.swing.JCheckBox();
        Sofa_Quantity = new javax.swing.JSpinner();
        Cupboard_Quantity = new javax.swing.JSpinner();
        DinningTable_Quantity = new javax.swing.JSpinner();
        Chairs_Quantity = new javax.swing.JSpinner();
        ArmChair_Quantity = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        Chairs_Total = new javax.swing.JFormattedTextField();
        Sofa_Total = new javax.swing.JFormattedTextField();
        CoffeeTable_Total = new javax.swing.JFormattedTextField();
        DinningTable_Total = new javax.swing.JFormattedTextField();
        BedFrame_Total = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        ArmChair_Item = new javax.swing.JCheckBox();
        Cupboard_Item = new javax.swing.JCheckBox();
        ChestOfDrawers_Item = new javax.swing.JCheckBox();
        TVBench_Item = new javax.swing.JCheckBox();
        Desk_Item = new javax.swing.JCheckBox();
        ChestOfDrawers_Quantity = new javax.swing.JSpinner();
        CoffeeTable_Quantity = new javax.swing.JSpinner();
        Desk_Quantity = new javax.swing.JSpinner();
        BedFrame_Quantity = new javax.swing.JSpinner();
        TVBench_Quantity = new javax.swing.JSpinner();
        TVBench_Total = new javax.swing.JFormattedTextField();
        ArmChair_Total = new javax.swing.JFormattedTextField();
        ChestOfDrawers_Total = new javax.swing.JFormattedTextField();
        Desk_Total = new javax.swing.JFormattedTextField();
        Cupboard_Total = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");

        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("jCheckBoxMenuItem4");

        jCheckBoxMenuItem5.setSelected(true);
        jCheckBoxMenuItem5.setText("jCheckBoxMenuItem5");

        checkbox1.setLabel("checkbox1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel4.setText("jLabel4");

        jLabel6.setText("$");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(0, 0, 0));

        Sofa_Item.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        Sofa_Item.setText("Sofa");
        Sofa_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sofa_ItemActionPerformed(evt);
            }
        });

        BedFrame_Item.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        BedFrame_Item.setText("Bed Frame");
        BedFrame_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BedFrame_ItemActionPerformed(evt);
            }
        });

        Next_Button.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        Next_Button.setText("Next");
        Next_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_ButtonActionPerformed(evt);
            }
        });

        CoffeeTable_Item.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        CoffeeTable_Item.setText("Coffee Table");
        CoffeeTable_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoffeeTable_ItemActionPerformed(evt);
            }
        });

        Chairs_Item.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        Chairs_Item.setText("Chairs");
        Chairs_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chairs_ItemActionPerformed(evt);
            }
        });

        DinningTable_Item.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        DinningTable_Item.setText("Dinning Table");
        DinningTable_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DinningTable_ItemActionPerformed(evt);
            }
        });

        Sofa_Quantity.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        Sofa_Quantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        Sofa_Quantity.setEnabled(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, Sofa_Quantity, org.jdesktop.beansbinding.ELProperty.create("${value}"), Sofa_Quantity, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        Sofa_Quantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Sofa_QuantityStateChanged(evt);
            }
        });

        Cupboard_Quantity.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        Cupboard_Quantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 40, 1));
        Cupboard_Quantity.setEnabled(false);
        Cupboard_Quantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Cupboard_QuantityStateChanged(evt);
            }
        });

        DinningTable_Quantity.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        DinningTable_Quantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 40, 1));
        DinningTable_Quantity.setEnabled(false);
        DinningTable_Quantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                DinningTable_QuantityStateChanged(evt);
            }
        });

        Chairs_Quantity.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        Chairs_Quantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 30, 1));
        Chairs_Quantity.setToolTipText("");
        Chairs_Quantity.setEnabled(false);
        Chairs_Quantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Chairs_QuantityStateChanged(evt);
            }
        });

        ArmChair_Quantity.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        ArmChair_Quantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        ArmChair_Quantity.setEnabled(false);
        ArmChair_Quantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ArmChair_QuantityStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        jLabel1.setText("Please select the items you wish to purchase and the quantity.");

        Chairs_Total.setEditable(false);
        Chairs_Total.setEnabled(false);
        Chairs_Total.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N

        Sofa_Total.setEditable(false);
        Sofa_Total.setEnabled(false);
        Sofa_Total.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        Sofa_Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sofa_TotalActionPerformed(evt);
            }
        });

        CoffeeTable_Total.setEditable(false);
        CoffeeTable_Total.setEnabled(false);
        CoffeeTable_Total.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        CoffeeTable_Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoffeeTable_TotalActionPerformed(evt);
            }
        });

        DinningTable_Total.setEditable(false);
        DinningTable_Total.setEnabled(false);
        DinningTable_Total.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        DinningTable_Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DinningTable_TotalActionPerformed(evt);
            }
        });

        BedFrame_Total.setEditable(false);
        BedFrame_Total.setEnabled(false);
        BedFrame_Total.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        jLabel13.setText("Once completed please click 'Next' to continue to proceed to checkout.");

        Back.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        ArmChair_Item.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        ArmChair_Item.setText("Arm Chair");
        ArmChair_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArmChair_ItemActionPerformed(evt);
            }
        });

        Cupboard_Item.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        Cupboard_Item.setText("Cupboard");
        Cupboard_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cupboard_ItemActionPerformed(evt);
            }
        });

        ChestOfDrawers_Item.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        ChestOfDrawers_Item.setText("Chest of Drawers");
        ChestOfDrawers_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChestOfDrawers_ItemActionPerformed(evt);
            }
        });

        TVBench_Item.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        TVBench_Item.setText("TV Bench");
        TVBench_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TVBench_ItemActionPerformed(evt);
            }
        });

        Desk_Item.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        Desk_Item.setText("Desk");
        Desk_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Desk_ItemActionPerformed(evt);
            }
        });

        ChestOfDrawers_Quantity.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        ChestOfDrawers_Quantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        ChestOfDrawers_Quantity.setEnabled(false);
        ChestOfDrawers_Quantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ChestOfDrawers_QuantityStateChanged(evt);
            }
        });

        CoffeeTable_Quantity.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        CoffeeTable_Quantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 40, 1));
        CoffeeTable_Quantity.setEnabled(false);
        CoffeeTable_Quantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CoffeeTable_QuantityStateChanged(evt);
            }
        });

        Desk_Quantity.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        Desk_Quantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 40, 1));
        Desk_Quantity.setEnabled(false);
        Desk_Quantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Desk_QuantityStateChanged(evt);
            }
        });

        BedFrame_Quantity.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        BedFrame_Quantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 30, 1));
        BedFrame_Quantity.setToolTipText("");
        BedFrame_Quantity.setEnabled(false);
        BedFrame_Quantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BedFrame_QuantityStateChanged(evt);
            }
        });

        TVBench_Quantity.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        TVBench_Quantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 70, 1));
        TVBench_Quantity.setEnabled(false);
        TVBench_Quantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TVBench_QuantityStateChanged(evt);
            }
        });

        TVBench_Total.setEditable(false);
        TVBench_Total.setEnabled(false);
        TVBench_Total.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        TVBench_Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TVBench_TotalActionPerformed(evt);
            }
        });

        ArmChair_Total.setEditable(false);
        ArmChair_Total.setEnabled(false);
        ArmChair_Total.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        ArmChair_Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArmChair_TotalActionPerformed(evt);
            }
        });

        ChestOfDrawers_Total.setEditable(false);
        ChestOfDrawers_Total.setEnabled(false);
        ChestOfDrawers_Total.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        ChestOfDrawers_Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChestOfDrawers_TotalActionPerformed(evt);
            }
        });

        Desk_Total.setEditable(false);
        Desk_Total.setEnabled(false);
        Desk_Total.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        Desk_Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Desk_TotalActionPerformed(evt);
            }
        });

        Cupboard_Total.setEditable(false);
        Cupboard_Total.setEnabled(false);
        Cupboard_Total.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        jLabel5.setText("$25.99");

        jLabel7.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        jLabel7.setText("$61.99");

        jLabel8.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        jLabel8.setText("$25.99");

        jLabel9.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        jLabel9.setText("$51.99");

        jLabel11.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        jLabel11.setText("$34.99");

        jLabel14.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        jLabel14.setText("$55.99");

        jLabel15.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        jLabel15.setText("$54.99");

        jLabel16.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        jLabel16.setText("$70.99");

        jLabel17.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        jLabel17.setText("$47.99");

        jLabel18.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        jLabel18.setText("$63.99");

        jLabel19.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        jLabel19.setText("$");

        jLabel29.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        jLabel29.setText("$");

        jLabel30.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        jLabel30.setText("$");

        jLabel31.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        jLabel31.setText("$");

        jLabel32.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        jLabel32.setText("$");

        jLabel33.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        jLabel33.setText("$");

        jLabel34.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        jLabel34.setText("$");

        jLabel35.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        jLabel35.setText("$");

        jLabel36.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        jLabel36.setText("$");

        jLabel37.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        jLabel37.setText("$");

        jLabel10.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        jLabel10.setText("Item(s)");

        jLabel12.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        jLabel12.setText("Quantity");

        jLabel38.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        jLabel38.setText("Total");

        jLabel39.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        jLabel39.setText("Price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel13)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Next_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BedFrame_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CoffeeTable_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Cupboard_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Desk_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DinningTable_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sofa_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TVBench_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Chairs_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ChestOfDrawers_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ArmChair_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel10)))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ArmChair_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BedFrame_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Chairs_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ChestOfDrawers_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CoffeeTable_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Cupboard_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Desk_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DinningTable_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sofa_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TVBench_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel17))
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel29)
                                            .addComponent(jLabel30)
                                            .addComponent(jLabel31)
                                            .addComponent(jLabel32)
                                            .addComponent(jLabel33)
                                            .addComponent(jLabel34)
                                            .addComponent(jLabel35)
                                            .addComponent(jLabel36)
                                            .addComponent(jLabel37))
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ArmChair_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Desk_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CoffeeTable_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ChestOfDrawers_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Cupboard_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(DinningTable_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Sofa_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TVBench_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Chairs_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BedFrame_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel39)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel38)
                                        .addGap(21, 21, 21)))))))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BedFrame_Item, Chairs_Item, CoffeeTable_Item, DinningTable_Item, Sofa_Item});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ArmChair_Quantity, Chairs_Quantity, Cupboard_Quantity, DinningTable_Quantity, Sofa_Quantity});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BedFrame_Total, Chairs_Total, CoffeeTable_Total, DinningTable_Total, Sofa_Total});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel38)
                            .addComponent(jLabel39))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ArmChair_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ArmChair_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel19))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BedFrame_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BedFrame_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Chairs_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Chairs_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ChestOfDrawers_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChestOfDrawers_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CoffeeTable_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CoffeeTable_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cupboard_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cupboard_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel33))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Desk_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Desk_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DinningTable_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DinningTable_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Sofa_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sofa_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TVBench_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TVBench_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel37)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ArmChair_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(BedFrame_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(205, 205, 205)
                                .addComponent(DinningTable_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Sofa_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TVBench_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Chairs_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ChestOfDrawers_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CoffeeTable_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(Cupboard_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(Desk_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Back)
                    .addComponent(Next_Button))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ArmChair_Quantity, BedFrame_Item, Chairs_Item, Chairs_Quantity, CoffeeTable_Item, Cupboard_Quantity, DinningTable_Item, DinningTable_Quantity, Sofa_Item, Sofa_Quantity});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BedFrame_Total, Chairs_Total, CoffeeTable_Total, DinningTable_Total, Sofa_Total});

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Sofa_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sofa_ItemActionPerformed
        
        if (Sofa_Item.isSelected()) {
            Sofa_Quantity.setEnabled(true);            //Makes field visible
            Sofa_Total.setEnabled(true);               //Makes field visible
            
        } 
       
        
        else{
            Sofa_Quantity.setEnabled(false);
            Sofa_Total.setEnabled(false);
            Sofa_Quantity.setValue(0);
        }
    }//GEN-LAST:event_Sofa_ItemActionPerformed

    private void CoffeeTable_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoffeeTable_ItemActionPerformed
        if (CoffeeTable_Item.isSelected()) 
        {
            CoffeeTable_Quantity.setEnabled(true);  //Makes field visible
            CoffeeTable_Total.setEnabled(true);     //Makes field visible
        } 
        
        else 
        {
            CoffeeTable_Quantity.setEnabled(false);
            CoffeeTable_Total.setEnabled(false);
            CoffeeTable_Quantity.setValue(0);
        }
    }//GEN-LAST:event_CoffeeTable_ItemActionPerformed

    private void Chairs_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chairs_ItemActionPerformed
        if (Chairs_Item.isSelected()) 
        {
            Chairs_Quantity.setEnabled(true); //Makes field visible
            Chairs_Total.setEnabled(true);    //Makes field visible
        } 
        
        else 
        {
            Chairs_Quantity.setEnabled(false);
            Chairs_Total.setEnabled(false);
            Chairs_Quantity.setValue(0);
        }
    }//GEN-LAST:event_Chairs_ItemActionPerformed

    private void DinningTable_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DinningTable_ItemActionPerformed
        if (DinningTable_Item.isSelected()) 
        {
            DinningTable_Quantity.setEnabled(true);   //Makes field visible
            DinningTable_Total.setEnabled(true);      //Makes field visible
        } 
        
        else 
        {
         DinningTable_Quantity.setEnabled(false);
         DinningTable_Total.setEnabled(false);   
         DinningTable_Quantity.setValue(0);
        }
    }//GEN-LAST:event_DinningTable_ItemActionPerformed

    private void BedFrame_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BedFrame_ItemActionPerformed
        if (BedFrame_Item.isSelected()) 
        {
            BedFrame_Quantity.setEnabled(true);       //Makes field visible    
            BedFrame_Total.setEnabled(true);          //Makes field visible
        } 
        
        else 
        {
            BedFrame_Quantity.setEnabled(false);         
            BedFrame_Total.setEnabled(false);
            BedFrame_Quantity.setValue(0);
        }
    }//GEN-LAST:event_BedFrame_ItemActionPerformed

    private void CoffeeTable_TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoffeeTable_TotalActionPerformed
        
    }//GEN-LAST:event_CoffeeTable_TotalActionPerformed

    private void DinningTable_TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DinningTable_TotalActionPerformed

    }//GEN-LAST:event_DinningTable_TotalActionPerformed

    private void Sofa_TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sofa_TotalActionPerformed
     
    }//GEN-LAST:event_Sofa_TotalActionPerformed

    private void Next_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_ButtonActionPerformed
       Customer_Checkout_Error cSE = new Customer_Checkout_Error();
       Customer_Checkout f = new Customer_Checkout();
       DecimalFormat fmt = new DecimalFormat("0.00");
       
       double input1  =  Double.parseDouble  (ArmChair_Total.getText());       //parses Arm Chair Total String as Double
       double input2  =  Double.parseDouble  (BedFrame_Total.getText());        //parses Bed Frame Total String as Double
       double input3  =  Double.parseDouble  (Chairs_Total.getText());          //parses Chairs Table Total String as Double
       double input4  =  Double.parseDouble  (ChestOfDrawers_Total.getText());  //parses Chest of Drawers Total String as Double
       double input5  =  Double.parseDouble  (CoffeeTable_Total.getText());     //parses Coffee Table Total String as Double
       double input6  =  Double.parseDouble  (Cupboard_Total.getText() );       //parses Cupboard Total String as Double
       double input7  =  Double.parseDouble  (Desk_Total.getText());            //parses Desk Total String as Double
       double input8  =  Double.parseDouble  (DinningTable_Total.getText());    //parses Dinning Table Total String as Double
       double input9  =  Double.parseDouble  (Sofa_Total.getText());            //parses Sofa Total String as Double
       double input10 =  Double.parseDouble  (TVBench_Total.getText());         //parses TV Bench Total String as Double
       
       double subtotal = (input1 + input2 + input3 + input4 + input5 + input6 + input7 + input8 + input9 + input10);
       double taxAmount = (subtotal * 0.16);
       double Total = ((taxAmount + subtotal)) ;
       
       Customer_Checkout.Final.setText(
                "Item\t\tQuantity\tTotal"  +
                "\n----------------------------------------------------------"      +
                "\nArm Chair\t\t      "          + this.ArmChair_Quantity.getValue()        + "\t$" + this.ArmChair_Total.getText()        + 
                "\nBed Frame\t\t      "          + this.BedFrame_Quantity.getValue()        + "\t$" + this.BedFrame_Total.getText()        +
                "\nChairs\t\t      "             + this.Chairs_Quantity.getValue()          + "\t$" + this.Chairs_Total.getText()          +
                "\nChest of Drawers\t      "     + this.ChestOfDrawers_Quantity.getValue()  + "\t$" + this.ChestOfDrawers_Total.getText()  +
                "\nCoffee Table\t\t      "       + this.CoffeeTable_Quantity.getValue()     + "\t$" + this.CoffeeTable_Total.getText()     +
                "\nCupboard\t\t      "           + this.Cupboard_Quantity.getValue()        + "\t$" + this.Cupboard_Total.getText()        + 
                "\nDesk\t\t      "               + this.Desk_Quantity.getValue()            + "\t$" + this.Desk_Total.getText()            +
                "\nDinning Table\t\t      "      + this.DinningTable_Quantity.getValue()    + "\t$" + this.DinningTable_Total.getText()    +
                "\nSofa\t\t      "               + this.Sofa_Quantity.getValue()            + "\t$" + this.Sofa_Total.getText()            +
                "\nTV Bench\t\t      "           + this.TVBench_Quantity.getValue()         + "\t$" + this.TVBench_Total.getText()         +
                "\n----------------------------------------------------------"    +
                "\nSubTotal\t\t$"       + fmt.format(subtotal)                     +
                "\n16% GST\t\t$"         + fmt.format(taxAmount)                    +
                "\nTotal\t\t$"          + fmt.format(Total)
                ); // sends text values and input to next interface as button is pressed
        
       Stored_Total.setTotal(fmt.format(Total));
       
       int AC = (Integer)ArmChair_Quantity.getValue();
       Item_Arm_Chair.UpdateQuantity(AC);
       
       int BF = (Integer)BedFrame_Quantity.getValue();
       Item_Bed_Frame.UpdateQuantity(BF);
       
       int Ch = (Integer)Chairs_Quantity.getValue();
       Item_Chairs.UpdateQuantity(Ch);
       
       int CoD = (Integer)ChestOfDrawers_Quantity.getValue();
       Item_Chest_of_Drawers.UpdateQuantity(CoD);
       
       int CT = (Integer)CoffeeTable_Quantity.getValue();
       Item_Coffee_Table.UpdateQuantity(CT);
       
       int Cu = (Integer)Cupboard_Quantity.getValue();
       Item_Cupboard.UpdateQuantity(Cu);
       
       int D = (Integer)Desk_Quantity.getValue();
       Item_Desk.UpdateQuantity(D);
       
       int DT = (Integer)DinningTable_Quantity.getValue();
       Item_Dinning_Table.UpdateQuantity(DT);
       
       int S = (Integer)Sofa_Quantity.getValue();
       Item_Sofa.UpdateQuantity(S);
       
       int TB = (Integer)TVBench_Quantity.getValue();
       Item_TV_Bench.UpdateQuantity(TB);
          
        if( ((Integer) this.ArmChair_Quantity.getValue() == 0) && ((Integer) this.BedFrame_Quantity.getValue() == 0) && ((Integer) this.Chairs_Quantity.getValue() == 0) && ((Integer) this.ChestOfDrawers_Quantity.getValue() == 0) && ((Integer) this.CoffeeTable_Quantity.getValue() == 0) && ((Integer) this.Cupboard_Quantity.getValue() == 0) && ((Integer) this.Desk_Quantity.getValue() == 0) && ((Integer) this.DinningTable_Quantity.getValue() == 0) && ((Integer) this.Sofa_Quantity.getValue() == 0) && ((Integer) this.TVBench_Quantity.getValue() == 0))
        {
            cSE.setVisible(true);
        }
        
        else
        {
        this.setVisible(false);
        f.setVisible(true);
        }
    }//GEN-LAST:event_Next_ButtonActionPerformed
    
    
    private void Sofa_QuantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Sofa_QuantityStateChanged
       Item_Sofa iS = new Item_Sofa();
       DecimalFormat fmt = new DecimalFormat("0.00");
        
       int quantity = (Integer)Sofa_Quantity.getValue();
       
       Sofa_Total.setText(fmt.format(quantity * iS.getPrice())); //calculates Total Price
    }//GEN-LAST:event_Sofa_QuantityStateChanged

    private void Cupboard_QuantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Cupboard_QuantityStateChanged
       Item_Cupboard iC = new Item_Cupboard();
       DecimalFormat fmt = new DecimalFormat("0.00");
        
       int quantity = (Integer)Cupboard_Quantity.getValue();
       
       Cupboard_Total.setText(fmt.format(iC.getPrice() * quantity)); //calculates Total Price
    }//GEN-LAST:event_Cupboard_QuantityStateChanged

    private void Chairs_QuantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Chairs_QuantityStateChanged
       Item_Chairs iC = new Item_Chairs();
       DecimalFormat fmt = new DecimalFormat("0.00");
        
       int quantity = (Integer)Chairs_Quantity.getValue();
       
       Chairs_Total.setText(fmt.format(quantity * iC.getPrice())); //calculates Total Price
    }//GEN-LAST:event_Chairs_QuantityStateChanged

    private void DinningTable_QuantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_DinningTable_QuantityStateChanged
       Item_Dinning_Table iDT = new Item_Dinning_Table();
       DecimalFormat fmt = new DecimalFormat("0.00");
        
       int quantity = (Integer)DinningTable_Quantity.getValue();
     
       DinningTable_Total.setText(fmt.format(quantity * iDT.getPrice())); //calculates Total Price
    }//GEN-LAST:event_DinningTable_QuantityStateChanged

    private void ArmChair_QuantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ArmChair_QuantityStateChanged
       Item_Arm_Chair iAC = new Item_Arm_Chair();
       DecimalFormat fmt = new DecimalFormat("0.00");
        
       int quantity = (Integer)ArmChair_Quantity.getValue();  //calculates Total Price
       
       ArmChair_Total.setText(fmt.format(quantity * iAC.getPrice()));  //calculates Total Pric
    }//GEN-LAST:event_ArmChair_QuantityStateChanged

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        this.setVisible(false);
        Home_Interface f = new Home_Interface();
        f.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_BackActionPerformed

    private void ArmChair_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArmChair_ItemActionPerformed
        if (ArmChair_Item.isSelected()) 
        {
            ArmChair_Quantity.setEnabled(true);       //Makes field visible    
            ArmChair_Total.setEnabled(true);          //Makes field visible
        } 
        
        else 
        {
            ArmChair_Quantity.setEnabled(false);         
            ArmChair_Total.setEnabled(false);
            ArmChair_Quantity.setValue(0);
        }
    }//GEN-LAST:event_ArmChair_ItemActionPerformed

    private void Cupboard_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cupboard_ItemActionPerformed
        if (Cupboard_Item.isSelected()) 
        {
            Cupboard_Quantity.setEnabled(true);       //Makes field visible    
            Cupboard_Total.setEnabled(true);          //Makes field visible
        } 
        
        else 
        {
            Cupboard_Quantity.setEnabled(false);         
            Cupboard_Total.setEnabled(false);
            Cupboard_Quantity.setValue(0);
        }
    }//GEN-LAST:event_Cupboard_ItemActionPerformed

    private void ChestOfDrawers_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChestOfDrawers_ItemActionPerformed
        if (ChestOfDrawers_Item.isSelected()) 
        {
            ChestOfDrawers_Quantity.setEnabled(true);       //Makes field visible    
            ChestOfDrawers_Total.setEnabled(true);          //Makes field visible
        } 
        
        else 
        {
            ChestOfDrawers_Quantity.setEnabled(false);         
            ChestOfDrawers_Total.setEnabled(false);
            ChestOfDrawers_Quantity.setValue(0);
        }
    }//GEN-LAST:event_ChestOfDrawers_ItemActionPerformed

    private void TVBench_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TVBench_ItemActionPerformed
        if (TVBench_Item.isSelected()) {
            TVBench_Quantity.setEnabled(true);       //Makes field visible    
            TVBench_Total.setEnabled(true);          //Makes field visible
        } 
        
        else {
            TVBench_Quantity.setEnabled(false);         
            TVBench_Total.setEnabled(false);
            TVBench_Quantity.setValue(0);
        }
    }//GEN-LAST:event_TVBench_ItemActionPerformed

    private void Desk_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Desk_ItemActionPerformed
        if (Desk_Item.isSelected()) 
        {
            Desk_Quantity.setEnabled(true);       //Makes field visible    
            Desk_Total.setEnabled(true);          //Makes field visible
        } 
        
        else 
        {
            Desk_Quantity.setEnabled(false);         
            Desk_Total.setEnabled(false);            
            Desk_Quantity.setValue(0);
        }
    }//GEN-LAST:event_Desk_ItemActionPerformed

    private void ChestOfDrawers_QuantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ChestOfDrawers_QuantityStateChanged
       Item_Chest_of_Drawers iCoD = new Item_Chest_of_Drawers();
       DecimalFormat fmt = new DecimalFormat("0.00");
        
       int quantity = (Integer)ChestOfDrawers_Quantity.getValue();  //calculates Total Price
       
       ChestOfDrawers_Total.setText(fmt.format(quantity * iCoD.getPrice()));  //calculates Total Price
    }//GEN-LAST:event_ChestOfDrawers_QuantityStateChanged

    private void CoffeeTable_QuantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CoffeeTable_QuantityStateChanged
       Item_Coffee_Table iCT = new Item_Coffee_Table();
       DecimalFormat fmt = new DecimalFormat("0.00");
        
       int quantity = (Integer)CoffeeTable_Quantity.getValue();  //calculates Total Price
       
       CoffeeTable_Total.setText(fmt.format(quantity * iCT.getPrice()));  //calculates Total Price
    }//GEN-LAST:event_CoffeeTable_QuantityStateChanged

    private void Desk_QuantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Desk_QuantityStateChanged
       Item_Desk iD = new Item_Desk();
       DecimalFormat fmt = new DecimalFormat("0.00");
        
       int quantity = (Integer)Desk_Quantity.getValue();  //calculates Total Price
       
       Desk_Total.setText(fmt.format(quantity * iD.getPrice()));  //calculates Total Price
    }//GEN-LAST:event_Desk_QuantityStateChanged

    private void BedFrame_QuantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BedFrame_QuantityStateChanged
       Item_Bed_Frame iBF = new Item_Bed_Frame();
       DecimalFormat fmt = new DecimalFormat("0.00");
        
       int quantity = (Integer)BedFrame_Quantity.getValue();
   
       BedFrame_Total.setText(fmt.format(quantity * iBF.getPrice()));  //calculates Total Price
    }//GEN-LAST:event_BedFrame_QuantityStateChanged

    private void TVBench_QuantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TVBench_QuantityStateChanged
       Item_TV_Bench iTB = new Item_TV_Bench();
       DecimalFormat fmt = new DecimalFormat("0.00");
        
       int quantity = (Integer)TVBench_Quantity.getValue();  //calculates Value
       
       TVBench_Total.setText(fmt.format(quantity * iTB.getPrice()));  //calculates Total Price
    }//GEN-LAST:event_TVBench_QuantityStateChanged

    private void ArmChair_TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArmChair_TotalActionPerformed
        
    }//GEN-LAST:event_ArmChair_TotalActionPerformed

    private void ChestOfDrawers_TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChestOfDrawers_TotalActionPerformed

    }//GEN-LAST:event_ChestOfDrawers_TotalActionPerformed

    private void Desk_TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Desk_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Desk_TotalActionPerformed

    private void TVBench_TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TVBench_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TVBench_TotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_Select().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ArmChair_Item;
    public javax.swing.JSpinner ArmChair_Quantity;
    public javax.swing.JFormattedTextField ArmChair_Total;
    private javax.swing.JButton Back;
    private javax.swing.JCheckBox BedFrame_Item;
    public javax.swing.JSpinner BedFrame_Quantity;
    public javax.swing.JFormattedTextField BedFrame_Total;
    private javax.swing.JCheckBox Chairs_Item;
    public javax.swing.JSpinner Chairs_Quantity;
    public javax.swing.JFormattedTextField Chairs_Total;
    private javax.swing.JCheckBox ChestOfDrawers_Item;
    public javax.swing.JSpinner ChestOfDrawers_Quantity;
    public javax.swing.JFormattedTextField ChestOfDrawers_Total;
    private javax.swing.JCheckBox CoffeeTable_Item;
    public javax.swing.JSpinner CoffeeTable_Quantity;
    public javax.swing.JFormattedTextField CoffeeTable_Total;
    private javax.swing.JCheckBox Cupboard_Item;
    public javax.swing.JSpinner Cupboard_Quantity;
    public javax.swing.JFormattedTextField Cupboard_Total;
    private javax.swing.JCheckBox Desk_Item;
    public javax.swing.JSpinner Desk_Quantity;
    public javax.swing.JFormattedTextField Desk_Total;
    private javax.swing.JCheckBox DinningTable_Item;
    public javax.swing.JSpinner DinningTable_Quantity;
    public javax.swing.JFormattedTextField DinningTable_Total;
    public static javax.swing.JButton Next_Button;
    private javax.swing.JCheckBox Sofa_Item;
    public javax.swing.JSpinner Sofa_Quantity;
    public javax.swing.JFormattedTextField Sofa_Total;
    private javax.swing.JCheckBox TVBench_Item;
    public javax.swing.JSpinner TVBench_Quantity;
    public javax.swing.JFormattedTextField TVBench_Total;
    private java.awt.Checkbox checkbox1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem5;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
