/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package FinalProject;


import java.awt.Color;
import java.awt.Font;



/**
 *
 * @author Daanyaal
 */
public class Employee_Interface extends javax.swing.JFrame {

    /**
     * Creates new form Employee_Inventory
     */
    
    
    
    public Employee_Interface() {
        initComponents();
        setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back_Button = new javax.swing.JButton();
        New_Employee = new javax.swing.JButton();
        Check_Inventory = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ID_Number = new javax.swing.JLabel();
        Back_Button1 = new javax.swing.JButton();
        Check_Sales = new javax.swing.JButton();

        Back_Button.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        Back_Button.setText("Back");
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        New_Employee.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        New_Employee.setText("New Employee");
        New_Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_EmployeeActionPerformed(evt);
            }
        });

        Check_Inventory.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        Check_Inventory.setText("Check Inventory");
        Check_Inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check_InventoryActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("KG Blank Space Solid", 0, 18)); // NOI18N
        jLabel1.setText("Welcome,");

        ID_Number.setFont(new java.awt.Font("KG Blank Space Solid", 0, 18)); // NOI18N
        ID_Number.setAlignmentY(0.0F);
        ID_Number.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                ID_NumberInputMethodTextChanged(evt);
            }
        });

        Back_Button1.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        Back_Button1.setText("Log Out");
        Back_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_Button1ActionPerformed(evt);
            }
        });

        Check_Sales.setFont(new java.awt.Font("KG Blank Space Solid", 0, 12)); // NOI18N
        Check_Sales.setText("Check Sales");
        Check_Sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check_SalesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ID_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(Back_Button1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(New_Employee)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Check_Inventory)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Check_Sales)
                        .addGap(17, 17, 17)))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(ID_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Check_Inventory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Check_Sales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(New_Employee)
                .addGap(18, 18, 18)
                .addComponent(Back_Button1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void New_EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_EmployeeActionPerformed
        Employee_New_Employee eNE = new Employee_New_Employee();
        
        this.setVisible(false);
        eNE.setVisible(true);
    }//GEN-LAST:event_New_EmployeeActionPerformed

    private void ID_NumberInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_ID_NumberInputMethodTextChanged
        
    }//GEN-LAST:event_ID_NumberInputMethodTextChanged

    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed
        this.setVisible(false);
        Home_Interface f = new Home_Interface();
        f.setVisible(true);
    }//GEN-LAST:event_Back_ButtonActionPerformed

    private void Back_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_Button1ActionPerformed
        this.setVisible(false);
        Employee_Login f = new Employee_Login();
        f.setVisible(true);
    }//GEN-LAST:event_Back_Button1ActionPerformed

    private void Check_InventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check_InventoryActionPerformed
    Employee_Inventory eI = new Employee_Inventory();
    Font font = new Font("KG Blank Space Solid", Font.BOLD, 12);  //assigns new font
    
    int AC = Item_Arm_Chair.getQuantity();
    if (AC <= 10)
    {
        eI.ArmChair_Inventory.setBackground(Color.yellow);
        eI.ArmChair_Inventory.setForeground(Color.RED);
        eI.ArmChair_Inventory.setFont(font);
        eI.ArmChair_Inventory.setText(AC + "");   
    }
    else
    {
        eI.ArmChair_Inventory.setText(AC + "");
    }
       
    int BF = Item_Bed_Frame.getQuantity();
    if (BF <= 10)
    {
        eI.BedFrame_Inventory.setBackground(Color.yellow);
        eI.BedFrame_Inventory.setForeground(Color.RED);
        eI.BedFrame_Inventory.setFont(font);
        eI.BedFrame_Inventory.setText(BF + "");   
    }
    else
    {
        eI.BedFrame_Inventory.setText(BF + "");
    }
    
    int Ch = Item_Chairs.getQuantity();
    if (Ch <= 10)
    {
        eI.Chairs_Inventory.setBackground(Color.yellow);
        eI.Chairs_Inventory.setForeground(Color.RED);
        eI.Chairs_Inventory.setFont(font);
        eI.Chairs_Inventory.setText(Ch + "");   
    }
    else
    {
        eI.Chairs_Inventory.setText(Ch + "");
    }
    
    int CoD = Item_Chest_of_Drawers.getQuantity();
    if (CoD <= 10)
    {
        eI.ChestOfDrawers_Inventory.setBackground(Color.yellow);
        eI.ChestOfDrawers_Inventory.setForeground(Color.RED);
        eI.ChestOfDrawers_Inventory.setFont(font);
        eI.ChestOfDrawers_Inventory.setText(CoD + "");   
    }
    else
    {
        eI.ChestOfDrawers_Inventory.setText(CoD + "");
    }
       
    int CT = Item_Coffee_Table.getQuantity();
    if (CT <= 10)
    {
        eI.CoffeeTable_Inventory.setBackground(Color.yellow);
        eI.CoffeeTable_Inventory.setForeground(Color.RED);
        eI.CoffeeTable_Inventory.setFont(font);
        eI.CoffeeTable_Inventory.setText(CT + "");   
    }
    else
    {
        eI.CoffeeTable_Inventory.setText(CT + "");
    }
       
    int Cu = Item_Cupboard.getQuantity();
    if (Cu <= 10)
    {
        eI.Cupboard_Inventory.setBackground(Color.yellow);
        eI.Cupboard_Inventory.setForeground(Color.RED);
        eI.Cupboard_Inventory.setFont(font);
        eI.Cupboard_Inventory.setText(Cu + "");   
    }
    else
    {
        eI.Cupboard_Inventory.setText(Cu + "");
    }
       
    int D = Item_Desk.getQuantity();
    if (D <= 10)
    {
        eI.Desk_Inventory.setBackground(Color.yellow);
        eI.Desk_Inventory.setForeground(Color.RED);
        eI.Desk_Inventory.setFont(font);
        eI.Desk_Inventory.setText(D + "");   
    }
    else
    {
        eI.Desk_Inventory.setText(D + "");
    }
       
    int DT = Item_Dinning_Table.getQuantity();
    if (DT <= 10)
    {
        eI.DinningTable_Inventory.setBackground(Color.yellow);
        eI.DinningTable_Inventory.setForeground(Color.RED);
        eI.DinningTable_Inventory.setFont(font);
        eI.DinningTable_Inventory.setText(DT + "");   
    }
    else
    {
        eI.DinningTable_Inventory.setText(DT + "");
    }
       
    int S = Item_Sofa.getQuantity();
    if (S <= 10)
    {
        eI.Sofa_Inventory.setBackground(Color.yellow);
        eI.Sofa_Inventory.setForeground(Color.RED);
        eI.Sofa_Inventory.setFont(font);
        eI.Sofa_Inventory.setText(S + "");   
    }
    else
    {
        eI.Sofa_Inventory.setText(S + "");
    }
       
    int TB = Item_TV_Bench.getQuantity();
    if (TB <= 10)
    {
        eI.TVBench_Inventory.setBackground(Color.yellow);
        eI.TVBench_Inventory.setForeground(Color.RED);
        eI.TVBench_Inventory.setFont(font);
        eI.TVBench_Inventory.setText(TB + "");   
    }
    else
    {
        eI.TVBench_Inventory.setText(TB + "");
    }
    
        
    this.setVisible(false);
    eI.setVisible(true);
    }//GEN-LAST:event_Check_InventoryActionPerformed

    private void Check_SalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check_SalesActionPerformed
      Employee_Sales eS = new Employee_Sales();
   
      int count = Transaction_Counter.getCount();      
      for(int i = 1; i <= count; i++)
      {
          eS.Transactions.addItem("Transaction " + i + " - " + Transaction_Date.getSpecificValue(i-1));
      }
       
        this.setVisible(false);
        eS.setVisible(true);
    }//GEN-LAST:event_Check_SalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Button;
    private javax.swing.JButton Back_Button1;
    public static javax.swing.JButton Check_Inventory;
    private javax.swing.JButton Check_Sales;
    public javax.swing.JLabel ID_Number;
    public javax.swing.JButton New_Employee;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
